# Generated by Django 5.0.7 on 2024-08-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_content_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.BooleanField(choices=[(1, 'Upvote'), (0, 'Downvote')]),
        ),
    ]
