# Generated by Django 5.1 on 2024-08-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.TextField(default='media/profilePricture/default.svg'),
        ),
    ]
