# Generated by Django 5.1 on 2024-08-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='media/profilePricture/default.svg', upload_to='media/profilePicture'),
        ),
    ]
