# Generated by Django 5.0.7 on 2024-08-20 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexispace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='flexispace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_to', to='flexispace.flexispace'),
        ),
    ]
